In [8]:
import argparse
import statistics
import numpy as np
import pandas as pd

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer

from sklearn.metrics import classification_report

#data = pd.read_csv('ISEAR-nli-prompt-emotion3-deberta.csv')
#ISEAR_nli_Deberta_prompt2.csv
#ISEAR-nli-prompt-emotion-roberta.csv
#TEC_nli-deberta-feels-emo.csv
#data = pd.read_csv('TEC_nli_prompt-emotion-prediction_file_deberta2.csv')
data = pd.read_csv('Isear_nli_syn_avg_expr_prompt.csv')
#Isear_nli_syn_avg_feels_prompt.csv
data = pd.read_csv('Isear_nli_syn_avg_feels_prompt.csv')
#data2 = pd.read_csv('TEC2_roberta_nli2.csv')
#data3=pd.read_csv('TEC2_roberta_nli2.csv')
y_true = data['labels'].tolist()
text=data['text'].tolist()
#y_pred = data['prob_expr_s'].tolist()
probs=data['prob_feels_s'].tolist()
max_probs=list()

#for m in probs:
#    max_probs.append(max(m))

for m in probs:
    m = m.strip("[]")

# Step 2: Split the string by commas
    string_elements = m.split(",")

# Step 3: Convert each element to a float
    float_list = [float(element) for element in string_elements]
    
#    r=list(m)
#    print(m)
#    for d in float_list:
 #       arr = [float(i) for i in d[1:-1].split(",")]
 #       max_index=np.argmax(arr)
    max_probs.append(max(float_list))    
data['prob_max']=max_probs
data.to_csv('Isear_nli_syn_avg_feels_prompt2.csv', index=False)

In [10]:
import argparse
import statistics
import numpy as np
import pandas as pd

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer

from sklearn.metrics import classification_report

import statistics

data = pd.read_csv('Isear_nli_syn_avg_emotion_prompt2.csv')
#Isear_nli_syn_avg_emo_s_prompt2.csv  0.034
#Isear_nli_syn_avg_emotion_prompt2.csv  0.017
var=statistics.variance(data['prob_max'])
print(var)

0.01796317802699985


In [11]:
unique_labels = sorted(list(set(label_list)))
print(unique_labels)

['anger', 'disgust', 'fear', 'guilt', 'joy', 'sadness', 'shame']


In [61]:
import argparse
import statistics
import numpy as np
import pandas as pd

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer

from sklearn.metrics import classification_report

import statistics
from scipy.stats import entropy

#Isear_nli_syn_avg_emo_s_prompt.csv
data = pd.read_csv('Isear_nli_syn_avg_emotion_prompt2.csv')
data=pd.read_csv('Isear_nli_syn_avg_emotion_prompt2.csv')
data=pd.read_csv('Isear_nli_syn_avg_emo_s_prompt.csv')
data=pd.read_csv('Isear_nli_syn_avg_feels_prompt2.csv')

#Isear_nli_syn_avg_expr_prompt2
#Isear_nli_syn_avg_emo_s_prompt2.csv  0.034
#Isear_nli_syn_avg_emotion_prompt2.csv  0.017
y_true = data['labels'].tolist()
y_predict=data['feels_s'].tolist()
text=data['text'].tolist()
probs=data['prob_feels_s'].tolist()
probs2=list()



for i in range(len(y_true)):
    if y_predict[i]!=y_true[i] and y_true[i]=='shame':
        m=probs[i]
        m = m.strip("[]")

# Step 2: Split the string by commas
        string_elements = m.split(",")

# Step 3: Convert each element to a float
        float_list = [float(element) for element in string_elements]
        probs2.append(float_list[6])

ss=statistics.mean(probs2)
var=statistics.variance(probs2)
print(ss)
print(var)


#wrong prediction
#emo_s
#'anger', 'disgust', 'fear', 'guilt', 'joy', 'sadness', 'shame'
#anger:0.53, 0.47,0.47, 0.56, 0.23,0.45, 0.47
#angr:0.02, 0.05

#emotion prompt
#anger:0.71, disgust:0.62, fear:0.68, guilt:0.75, joy:0.35, sadness:0.6, shame:0.45
#anger:0.03, disgust:0.05, fear:0.04, guilt:0.02, joy:0.04, sadness:0.05  ,shame:0.06

#expr_s
# anger:0.7, disgust:0.65 fear:0.62 guilt:0.71  joy:0.31  sadness:0.64  shame:0.61
#0.04  0.06  0.07  0.04  0.05  0.06   0.06

#feels_s
#anger:0.77 disgust:0.67 fear:0.73 guilt:0.75   sadness:0.75 joy:0.48  shame:0.72
# 0.04  , 0.06 0.05  0.04  0.04 0.07 0.05

0.7215761470220254
0.05582110896620998


In [20]:
import argparse
import statistics
import numpy as np
import pandas as pd

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer

from sklearn.metrics import classification_report

import statistics
from scipy.stats import entropy

#Isear_nli_syn_avg_emo_s_prompt.csv
data = pd.read_csv('Isear_nli_syn_avg_emotion_prompt2.csv')
data=pd.read_csv('Isear_nli_syn_avg_emotion_prompt2.csv')
data=pd.read_csv('Isear_nli_syn_avg_emotion_prompt2.csv')
#data=pd.read_csv('Isear_nli_syn_avg_emo_s_prompt.csv')
data=pd.read_csv('Isear_nli_syn_avg_expr_prompt2.csv')
data=pd.read_csv('Isear_nli_syn_avg_feels_prompt2.csv')
data=pd.read_csv('Isear_nli_syn_avg_emo_s_prompt2.csv')
#Isear_nli_syn_avg_expr_prompt2.csv
#Isear_nli_syn_avg_emo_s_prompt2.csv  0.034
#Isear_nli_syn_avg_emotion_prompt2.csv  0.017
#Isear_nli_syn_expr_emo_promp_max_edited.csv
#Isear_nli_syn_avg_feels_prompt2.csv
#data=pd.read_csv('Isear_nli_syn_avg_emotion_prompt2.csv')

y_true = data['labels'].tolist()
y_predict=data['emo_s'].tolist()
text=data['text'].tolist()
probs=data['prob_emo_s'].tolist()
probs2=list()



for i in range(len(y_true)):
    if y_predict[i]==y_true[i] and y_true[i]=='shame':
        m=probs[i]
        m = m.strip("[]")

# Step 2: Split the string by commas
        string_elements = m.split(",")

# Step 3: Convert each element to a float
        float_list = [float(element) for element in string_elements]
        probs2.append(float_list[6])

ss=statistics.mean(probs2)
var=statistics.variance(probs2)
print(ss)
print(var)

#'anger', 'disgust', 'fear', 'guilt', 'joy', 'sadness', 'shame'
#'anger', 'disgust', 'fear', 'guilt', 'joy', 'sadness', 'shame'

#emo_s
#anger:0.81  disgust:0.77  fear:0.76  guilt:0.77 joy:0.72 sandess:0.76  shame:0.84
#0.02   0.03  0.03  0.03  0.02  0.03  0.018  0.022

#expr_s
#anger: 0.92,  disgust:0.91  , fear:0.91 , guilt:0.9  , joy:0.83 , sandess:0.91,  shame:0.93
#0.013 0.018 0.011  0.017  0.02  0.011  0.009


#emotion_s
#anger:0.87 disgust: 0.9  fear:0.9  guilt:0.86   joy: 0.83  sadness:0.88   shame:0.91  
# 0.008    0.01      0.01   0.01    0.012   0.008  0.1

#feels_s
#'anger' 0.92, 'disgust':0.85, 'fear'0.94, 'guilt'0.92, 'joy':0.9, 'sadness'0.93, 'shame' 0.96
#0.01  0.017  0.006  0.012  0.009  0.006  0.006

0.8412292122522743
0.02294825152319945


In [22]:
import argparse
import statistics
import numpy as np
import pandas as pd

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer

from sklearn.metrics import classification_report

import statistics
from scipy.stats import entropy

#Isear_nli_syn_avg_emo_s_prompt.csv
data = pd.read_csv('Isear_nli_syn_avg_emotion_prompt2.csv')
data=pd.read_csv('Isear_nli_syn_avg_emotion_prompt2.csv')
#data=pd.read_csv('Isear_nli_syn_avg_emo_s_prompt.csv')
#data=pd.read_csv('Isear_nli_syn_avg_feels_prompt2.csv')
#Isear_nli_syn_avg_expr_prompt2.csv
#Isear_nli_syn_avg_emo_s_prompt2.csv  0.034
#Isear_nli_syn_avg_emotion_prompt2.csv  0.017
#Isear_nli_syn_expr_emo_promp_max_edited.csv
#data=pd.read_csv('Isear_nli_syn_avg_emotion_prompt2.csv')

y_true = data['labels'].tolist()
y_predict=data['emotion'].tolist()
text=data['text'].tolist()
probs=data['prob_emotion'].tolist()
probs2=list()

unique_labels = sorted(list(set(label_list)))
print(unique_labels)

for i in range(len(y_true)):
    if y_true[i]=='anger':
        m=probs[i]
        m = m.strip("[]")

# Step 2: Split the string by commas
        string_elements = m.split(",")

# Step 3: Convert each element to a float
        float_list = [float(element) for element in string_elements]
        probs2.append(float_list[0])

#'anger', 'disgust', 'fear', 'guilt', 'joy', 'sadness', 'shame'        
ss=statistics.mean(probs2)
var=statistics.variance(probs2)
print(ss)
print(var)

0.7897746075121731
0.031739802589780854


In [2]:
import argparse
import statistics
import numpy as np
import pandas as pd

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer

from sklearn.metrics import classification_report

import statistics
from scipy.stats import entropy

#Isear_nli_syn_avg_emo_s_prompt.csv
data = pd.read_csv('Isear_nli_syn_avg_emotion_prompt2.csv')
data=pd.read_csv('Isear_nli_syn_avg_emotion_prompt2.csv')
#data=pd.read_csv('Isear_nli_syn_avg_emo_s_prompt.csv')
#data=pd.read_csv('Isear_nli_syn_avg_feels_prompt2.csv')
#Isear_nli_syn_avg_expr_prompt2.csv
#Isear_nli_syn_avg_emo_s_prompt2.csv  0.034
#Isear_nli_syn_avg_emotion_prompt2.csv  0.017
#Isear_nli_syn_expr_emo_promp_max_edited.csv
#data=pd.read_csv('Isear_nli_syn_avg_emotion_prompt2.csv')

y_true = data['labels'].tolist()
y_predict=data['emotion'].tolist()
text=data['text'].tolist()
probs=data['prob_emotion'].tolist()
probs2=list()

unique_labels = sorted(list(set(y_true)))
print(unique_labels)

for i in range(len(y_true)):
    if y_true[i]=='anger' and y_predict[i]=='anger':
        m=probs[i]
        m = m.strip("[]")

# Step 2: Split the string by commas
        string_elements = m.split(",")

# Step 3: Convert each element to a float
        float_list = [float(element) for element in string_elements]
        probs2.append(float_list[0])

#'anger', 'disgust', 'fear', 'guilt', 'joy', 'sadness', 'shame'        
ss=statistics.mean(probs2)
var=statistics.variance(probs2)
print(ss)
print(var)

['anger', 'disgust', 'fear', 'guilt', 'joy', 'sadness', 'shame']
0.8790193123411513
0.008569364215044034


In [2]:
import argparse
import statistics
import numpy as np
import pandas as pd

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import statistics

data = pd.read_csv('Isear_nli_syn_avg_emotion_prompt2.csv')
#data=pd.read_csv('Isear_nli_syn_avg_expr_prompt2.csv')
#data=pd.read_csv('Isear_nli_syn_avg_emo_s_prompt.csv')
##data=pd.read_csv('Isear_nli_syn_avg_feels_prompt2.csv')

l=data['labels']
p=data['emotion']
#print(confusion_matrix(l, p))
print(classification_report(l, p))

[[503  40  45 258   9  53 171]
 [157 415 119 191  24  38 122]
 [ 43  10 843 103  12  45  20]
 [ 98  17  28 719   9  62 116]
 [  4   1  21  49 994  17   6]
 [ 40  13  59 101  15 774  80]
 [ 63  27  59 347  26  39 510]]


In [41]:
import argparse
import statistics
import numpy as np
import pandas as pd

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from scipy.stats import entropy
from sklearn.metrics import classification_report

#data = pd.read_csv('ISEAR-nli-prompt-emotion3-deberta.csv')
#ISEAR_nli_Deberta_prompt2.csv
#ISEAR-nli-prompt-emotion-roberta.csv
#TEC_nli-deberta-feels-emo.csv
#data = pd.read_csv('TEC_nli_prompt-emotion-prediction_file_deberta2.csv')
data = pd.read_csv('Isear_nli_syn_avg_expr_prompt2.csv')

###
y_true = data['labels'].tolist()
y_predict=data['expr_s'].tolist()
text=data['text'].tolist()
probs=data['prob_expr_s'].tolist()
prob_max=data['prob_max'].tolist()
probs2=list()
entropy_list=list()
##
labels2=list()
expr_s2=list()
text2=list()
prob_max2=list()
prob2=list()

for i in range(len(y_true)):
    if y_predict[i]!=y_true[i] and y_true[i]=='sadness':
        m=probs[i]
        m = m.strip("[]")

# Step 2: Split the string by commas
        string_elements = m.split(",")

# Step 3: Convert each element to a float
        float_list = [float(element) for element in string_elements]
        
        e=entropy(float_list, base=2)
        entropy_list.append(e)
        ##
        labels2.append(y_true[i])
        expr_s2.append(y_predict[i])
        text2.append(text[i])
        prob2.append(probs[i])
        prob_max2.append(prob_max[i])

data2={'labels':labels2, 'text':text2, 'expr_s':expr_s2, 'prob_expr_s':prob2, 'prob_max':prob_max2, 'entropy':entropy_list}
d=pd.DataFrame(data2)

d.to_csv('Isear_nli_syn_avg_expr_prompt3.csv', index=False)

In [27]:
import argparse
import statistics
import numpy as np
import pandas as pd

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from scipy.stats import entropy
from sklearn.metrics import classification_report

#data = pd.read_csv('ISEAR-nli-prompt-emotion3-deberta.csv')
#ISEAR_nli_Deberta_prompt2.csv
#ISEAR-nli-prompt-emotion-roberta.csv
#TEC_nli-deberta-feels-emo.csv
#data = pd.read_csv('TEC_nli_prompt-emotion-prediction_file_deberta2.csv')
data = pd.read_csv('Isear_nli_syn_avg_expr_prompt2.csv')

###
y_true = data['labels'].tolist()
y_predict=data['expr_s'].tolist()
text=data['text'].tolist()
probs=data['prob_expr_s'].tolist()
prob_max=data['prob_max'].tolist()
probs2=list()
entropy_list=list()
##
labels2=list()
expr_s2=list()
text2=list()
prob_max2=list()
prob2=list()
var_list=list()

for i in range(len(y_true)):
#    if y_predict[i]!=y_true[i] and y_true[i]=='sadness':
    m=probs[i]
    m = m.strip("[]")

# Step 2: Split the string by commas
    string_elements = m.split(",")

# Step 3: Convert each element to a float
    float_list = [float(element) for element in string_elements]
        
#        e=entropy(float_list, base=2)
        
    var=statistics.variance(float_list)
    var_list.append(var)
#    entropy_list.append(e)
        ##
    labels2.append(y_true[i])
    expr_s2.append(y_predict[i])
    text2.append(text[i])
    prob2.append(probs[i])
    prob_max2.append(prob_max[i])

data2={'labels':labels2, 'text':text2, 'expr_s':expr_s2, 'prob_expr_s':prob2, 'prob_max':prob_max2, 'variance':var_list}
d=pd.DataFrame(data2)

d.to_csv('Isear_nli_syn_avg_expr_prompt2_new.csv', index=False)

In [30]:
import argparse
import statistics
import numpy as np
import pandas as pd

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from scipy.stats import entropy
from sklearn.metrics import classification_report

#data = pd.read_csv('ISEAR-nli-prompt-emotion3-deberta.csv')
#ISEAR_nli_Deberta_prompt2.csv
#ISEAR-nli-prompt-emotion-roberta.csv
#TEC_nli-deberta-feels-emo.csv
#data = pd.read_csv('TEC_nli_prompt-emotion-prediction_file_deberta2.csv')
data = pd.read_csv('Isear_nli_syn_avg_expr_prompt2.csv')
#Isear_nli_syn_avg_emo_s_prompt2.csv
data = pd.read_csv('Isear_nli_syn_avg_emo_s_prompt2.csv')

###
y_true = data['labels'].tolist()
y_predict=data['emo_s'].tolist()
text=data['text'].tolist()
probs=data['prob_emo_s'].tolist()
prob_max=data['prob_max'].tolist()
probs2=list()
entropy_list=list()
##
labels2=list()
expr_s2=list()
text2=list()
prob_max2=list()
prob2=list()
var_list=list()

for i in range(len(y_true)):
#    if y_predict[i]!=y_true[i] and y_true[i]=='sadness':
    m=probs[i]
    m = m.strip("[]")

# Step 2: Split the string by commas
    string_elements = m.split(",")

# Step 3: Convert each element to a float
    float_list = [float(element) for element in string_elements]
        
#        e=entropy(float_list, base=2)
        
    var=statistics.variance(float_list)
    var_list.append(var)
#    entropy_list.append(e)
        ##
    labels2.append(y_true[i])
    expr_s2.append(y_predict[i])
    text2.append(text[i])
    prob2.append(probs[i])
    prob_max2.append(prob_max[i])

data2={'labels':labels2, 'text':text2, 'emo_s':expr_s2, 'prob_emo_s':prob2, 'prob_max':prob_max2, 'variance':var_list}
d=pd.DataFrame(data2)

d.to_csv('Isear_nli_syn_avg_emo_s_prompt2_new.csv', index=False)

In [ ]:
import argparse
import statistics
import numpy as np
import pandas as pd

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from scipy.stats import entropy
from sklearn.metrics import classification_report

#data = pd.read_csv('ISEAR-nli-prompt-emotion3-deberta.csv')
#ISEAR_nli_Deberta_prompt2.csv
#ISEAR-nli-prompt-emotion-roberta.csv
#TEC_nli-deberta-feels-emo.csv
#data = pd.read_csv('TEC_nli_prompt-emotion-prediction_file_deberta2.csv')
data = pd.read_csv('Isear_nli_syn_avg_expr_prompt2.csv')
#Isear_nli_syn_avg_emo_s_prompt2.csv
#Isear_nli_syn_avg_expr_prompt2.csv

###
y_true = data['labels'].tolist()
y_predict=data['expr_s'].tolist()
text=data['text'].tolist()
probs=data['prob_expr_s'].tolist()
prob_max=data['prob_max'].tolist()
probs2=list()
entropy_list=list()
##
labels2=list()
expr_s2=list()
text2=list()
prob_max2=list()
prob2=list()

for i in range(len(y_true)):
    if y_predict[i]!=y_true[i] and y_true[i]=='sadness':
        m=probs[i]
        m = m.strip("[]")

# Step 2: Split the string by commas
        string_elements = m.split(",")

# Step 3: Convert each element to a float
        float_list = [float(element) for element in string_elements]
        
        e=entropy(float_list, base=2)
        entropy_list.append(e)
        ##
        labels2.append(y_true[i])
        expr_s2.append(y_predict[i])
        text2.append(text[i])
        prob2.append(probs[i])
        prob_max2.append(prob_max[i])

data2={'labels':labels2, 'text':text2, 'expr_s':expr_s2, 'prob_expr_s':prob2, 'prob_max':prob_max2, 'entropy':entropy_list}
d=pd.DataFrame(data2)

d.to_csv('Isear_nli_syn_avg_expr_prompt3.csv', index=False)

In [31]:
import argparse
import statistics
import numpy as np
import pandas as pd

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from scipy.stats import entropy
from sklearn.metrics import classification_report

#data = pd.read_csv('ISEAR-nli-prompt-emotion3-deberta.csv')
#ISEAR_nli_Deberta_prompt2.csv
#ISEAR-nli-prompt-emotion-roberta.csv
#TEC_nli-deberta-feels-emo.csv
#data = pd.read_csv('TEC_nli_prompt-emotion-prediction_file_deberta2.csv')
data = pd.read_csv('Isear_nli_syn_avg_emo_s_prompt2.csv')
#Isear_nli_syn_avg_emo_s_prompt2
###
y_true = data['labels'].tolist()
y_predict=data['emo_s'].tolist()
text=data['text'].tolist()
probs=data['prob_emo_s'].tolist()
prob_max=data['prob_max'].tolist()
probs2=list()
entropy_list=list()
##
labels2=list()
expr_s2=list()
text2=list()
prob_max2=list()
prob2=list()

for i in range(len(y_true)):
    
    m=probs[i]
    m = m.strip("[]")

# Step 2: Split the string by commas
    string_elements = m.split(",")

# Step 3: Convert each element to a float
    float_list = [float(element) for element in string_elements]
    float_list2=[(i)/max(float_list) for i in float_list]
    
        
    e=entropy(float_list2, base=2)
    
    entropy_list.append(e)
        ##
    labels2.append(y_true[i])
    expr_s2.append(y_predict[i])
    text2.append(text[i])
    prob2.append(probs[i])
    prob_max2.append(prob_max[i])

data2={'labels':labels2, 'text':text2, 'emo_s':expr_s2, 'prob_emo_s':prob2, 'prob_max':prob_max2, 'entropy':entropy_list}
d=pd.DataFrame(data2)

d.to_csv('Isear_nli_syn_avg_emo_prompt3.csv', index=False)

In [32]:
import argparse
import statistics
import numpy as np
import pandas as pd

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from scipy.stats import entropy
from sklearn.metrics import classification_report

#data = pd.read_csv('ISEAR-nli-prompt-emotion3-deberta.csv')
#ISEAR_nli_Deberta_prompt2.csv
#ISEAR-nli-prompt-emotion-roberta.csv
#TEC_nli-deberta-feels-emo.csv
#data = pd.read_csv('TEC_nli_prompt-emotion-prediction_file_deberta2.csv')

data = pd.read_csv('Isear_nli_syn_avg_emo_s_prompt3.csv')
y_true = data['labels'].tolist()
entropy_list=data['entropy'].tolist()
emo_s=data['emo_s'].tolist()
entropy_list2=list()

#'anger', 'disgust', 'fear', 'guilt', 'joy', 'sadness', 'shame'  


for i in range(len(y_true)):
    if y_true[i]=='guilt' and emo_s[i]!='guilt':
        entropy_list2.append(entropy_list[i])
mean=statistics.mean(entropy_list2)
print(mean) 

#True
#anger:2.54, disgust:2.582 fear:2.53 guilt:2.55

#wrong
#anger:2.58  disgust:2.586 fear:2.59 2.54

2.5486001700754906


In [10]:

class_counts=np.bincount(y_predicimport argparse
import statistics
import numpy as np
import pandas as pd

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from scipy.stats import entropy
from sklearn.metrics import classification_report
from scipy.stats import entropy

#'anger', 'disgust', 'fear', 'guilt', 'joy', 'sadness', 'shame' 
#data = pd.read_csv('ISEAR-nli-prompt-emotion3-deberta.csv')
#ISEAR_nli_Deberta_prompt2.csv
#ISEAR-nli-prompt-emotion-roberta.csv
#TEC_nli-deberta-feels-emo.csv
#data = pd.read_csv('TEC_nli_prompt-emotion-prediction_file_deberta2.csv')
#Isear_nli_syn_avg_expr_prompt2
data = pd.read_csv('Isear_nli_syn_avg_emo_s_prompt2.csv')
data = pd.read_csv('Isear_nli_syn_avg_expr_prompt2.csv')
dict_emo={'anger':0, 'disgust':1, 'fear':2, 'guilt':3, 'joy':4, 'sadness':5, 'shame':6 }
#Isear_nli_syn_avg_emo_s_prompt2
###
y_true = data['labels'].tolist()
y_predict=data['expr_s'].tolist()
probs=data['prob_expr_s'].tolist()
y_predict2=list()
probs2=list()
emotions=list()

for i in range(len(y_true)):
    if y_predict[i]!=y_true[i] and y_true[i]=='sadness':
        y_predict2.append(dict_emo[y_predict[i]])
        
probs=class_counts/len(y_predict2)
entropy_emotions=entropy(probs, base=2)
print(entropy_emotions)

#entropy, emo_s
#anger:1.62 disgust:2.1 fear:1.9 guilt:2.08 joy:1.77 sadness:2.05 shame:1.44

#entropy, expr_s
#anger:2.29    disgust: 2.26   fear:2.28  guilt:2.28  joy: 2.08  sadness:2.29   shame: 1.96

2.2953833108846884


In [1]:
import argparse
import statistics
import numpy as np
import pandas as pd

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from scipy.stats import entropy
from sklearn.metrics import classification_report
from scipy.stats import entropy

#'anger', 'disgust', 'fear', 'guilt', 'joy', 'sadness', 'shame' 
#data = pd.read_csv('ISEAR-nli-prompt-emotion3-deberta.csv')
#ISEAR_nli_Deberta_prompt2.csv
#ISEAR-nli-prompt-emotion-roberta.csv
#TEC_nli-deberta-feels-emo.csv
#data = pd.read_csv('TEC_nli_prompt-emotion-prediction_file_deberta2.csv')
#Isear_nli_syn_avg_expr_prompt2
data = pd.read_csv('Isear_nli_syn_avg_emo_s_prompt2.csv')
data = pd.read_csv('Isear_nli_syn_avg_expr_prompt2.csv')
dict_emo={'anger':0, 'disgust':1, 'fear':2, 'guilt':3, 'joy':4, 'sadness':5, 'shame':6 }
anger=0
disgust=0
fear=0 
guilt=0 
joy=0
sadness=0
shame=0 
#Isear_nli_syn_avg_emo_s_prompt2
###
y_true = data['labels'].tolist()
y_predict=data['expr_s'].tolist()
probs=data['prob_expr_s'].tolist()
y_predict2=list()
probs2=list()
emotions=list()

for i in range(len(y_true)):
    if y_predict[i]!=y_true[i] and y_true[i]=='anger':
        if y_predict[i]=='anger':
            anger+=1
        if y_predict[i]=='disgust':
            disgust+=1
        if y_predict[i]=='fear':
            fear+=1
        if y_predict[i]=='guilt':
            guilt+=1
        if y_predict[i]=='joy':
            joy+=1
        if y_predict[i]=='sadness':
            sadness+=1
        if y_predict[i]=='shame':
            shame+=1
print(anger)
print(disgust)
print(fear)
print(guilt)
print(joy)
print(sadness)
print(shame)
        

0
41
107
171
10
87
101


In [ ]:
import argparse
import statistics
import numpy as np
import pandas as pd

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer

from sklearn.metrics import classification_report

import statistics
from scipy.stats import entropy

#Isear_nli_syn_avg_emo_s_prompt.csv
#data = pd.read_csv('Isear_nli_syn_avg_emotion_prompt2.csv')
#data=pd.read_csv('Isear_nli_syn_avg_emotion_prompt2.csv')
#data=pd.read_csv('Isear_nli_syn_max_emotion_prompt.csv')
#Isear_nli_syn_avg_emotion_prompt2
data=pd.read_csv('Isear_nli_syn_avg_emotion_prompt2.csv')

l=data['labels'].tolist()
e=data['emotion'].tolist()
anger=0
disgust=0
fear=0
guilt=0
joy=0
sadness=0
shame=0

for i in range(len(l)):
    if l[i]=='shame':
        if e[i]=='anger':
            anger+=1
        if e[i]=='disgust':
            disgust+=1
        if e[i]=='fear':
            fear+=1
        if e[i]=='guilt':
            guilt+=1
        if e[i]=='joy':
            joy+=1
        if e[i]=='sadness':
            sadness+=1
        if e[i]=='shame':
            shame+=1
print(anger)
print(disgust)
print(fear)
print(guilt)
print(sadness)
print(shame)
print(joy)